{"mappings":"AAAA,MAAM,eAAe,GAAG,QAAQ,CAAC,aAAa,CAAC,SAAS,CAAC,AAAC;AAE1D,MAAM,OAAO,GAAG,SAAU,CAAC,EAAE;IAC3B,OAAO,IAAI,OAAO,CAAC,SAAU,CAAC,EAAE,MAAM,EAAE;QACtC,UAAU,CAAC,WAAY;YACrB,MAAM,CAAC,IAAI,KAAK,CAAC,CAAC,qCAAqC,EAAE,CAAC,CAAC,OAAO,CAAC,CAAC,CAAC,CAAC;SACvE,EAAE,CAAC,GAAG,IAAI,CAAC,CAAC;KACd,CAAC,CAAC;CACJ,AAAC;AAEF,uCAAuC;AACvC,gEAAgE;AAChE,8BAA8B;AAC9B,uCAAuC;AACvC,OAAO,CAAC,GAAG,CAAC,KAAK,CAAC,CAAC;AAEnB;;;;;;;;;;;;;;;GAeG,CAEH,MAAM,UAAU,GAAG,UAAY;IAC7B,IAAI;QACF,MAAM,QAAQ,GAAG,MAAM,KAAK,CAC1B,2EAA2E,CAC5E,AAAC;QAEF,MAAM,IAAI,GAAG,MAAM,QAAQ,CAAC,IAAI,EAAE,AAAC;QACnC,IAAI,CAAC,QAAQ,CAAC,EAAE,EAAE,MAAM,IAAI,KAAK,CAAC,CAAC,EAAE,IAAI,CAAC,OAAO,CAAC,CAAC,CAAC,CAAC;QACrD,IAAI,EAAE,MAAM,CAAA,EAAE,GAAG,IAAI,CAAC,IAAI,AAAC;QAE3B,OAAO,CAAC,GAAG,CAAC,MAAM,CAAC,CAAC;QAEpB,MAAM,GAAG;YACP,EAAE,EAAE,MAAM,CAAC,EAAE;YACb,WAAW,EAAE,MAAM,CAAC,YAAY;YAChC,QAAQ,EAAE,MAAM,CAAC,SAAS;YAC1B,WAAW,EAAE,MAAM,CAAC,WAAW;YAC/B,SAAS,EAAE,MAAM,CAAC,SAAS;YAC3B,QAAQ,EAAE,MAAM,CAAC,QAAQ;YACzB,SAAS,EAAE,MAAM,CAAC,UAAU;YAC5B,KAAK,EAAE,MAAM,CAAC,KAAK;SACpB,CAAC;QAEF,OAAO,CAAC,GAAG,CAAC,MAAM,CAAC,CAAC;KACrB,CAAC,OAAO,KAAK,EAAE;QACd,OAAO,CAAC,KAAK,CAAC,KAAK,CAAC,CAAC;KACtB;CACF,AAAC;AAEF,UAAU,EAAE,CAAC","sources":["src/js/controller.js"],"sourcesContent":["const recipeContainer = document.querySelector('.recipe');\n\nconst timeout = function (s) {\n  return new Promise(function (_, reject) {\n    setTimeout(function () {\n      reject(new Error(`Request took too long! Timeout after ${s} second`));\n    }, s * 1000);\n  });\n};\n\n// https://forkify-api.herokuapp.com/v2\n// https://forkify-api.herokuapp.com/api/v2/recipes?search=pizza\n// id=5ed6604591c37cdc054bcd09\n///////////////////////////////////////\nconsole.log('시작점');\n\n/**\n * ? 288강\n * 1.fetch API로 데이터 가져오기\n * 2.async await & json() 사용하기\n * 3.try-catch문 사용하기\n * 4.throw new Error() 사용하기\n * 5.데이터 recipe의 key 이름 전부 바꾸기\n *\n * todo\n * 1.Error 객체의 key가 stack, message가 있다는 것을 확인했다.\n * console.dir을 사용하면 확인 할 수 있다.\n *\n * 2.response.ok를 사용해서 throw new Error()를 사용해서 에러를\n * 발견하면 try-catch문에서 에러를 감지해서 catch문에 전달된다.\n *\n */\n\nconst showRecipe = async () => {\n  try {\n    const response = await fetch(\n      'https://forkify-api.herokuapp.com/api/v2/recipes/5ed6604591c37cdc054bcd09'\n    );\n\n    const data = await response.json();\n    if (!response.ok) throw new Error(`${data.message}`);\n    let { recipe } = data.data;\n\n    console.log(recipe);\n\n    recipe = {\n      id: recipe.id,\n      cookingTime: recipe.cooking_time,\n      imageUrl: recipe.image_url,\n      ingredients: recipe.ingredients,\n      publisher: recipe.publisher,\n      servings: recipe.servings,\n      sourceUrl: recipe.source_url,\n      title: recipe.title,\n    };\n\n    console.log(recipe);\n  } catch (error) {\n    console.error(error);\n  }\n};\n\nshowRecipe();\n"],"names":[],"version":3,"file":"index.62406edb.js.map","sourceRoot":"/__parcel_source_root/"}